### ISSUE TITLE
Why no "native" option for NodeJS?

### ISSUE THREAD

**Issue by anselanza** [yoctopuce/yoctolib_ts#2]
The Yoctopuce API seems very comprehensive (if, arguably, a little over-engineered) but I am curious why NodeJS is left with the need to connect (via Websocket) to a VirtualHub instance (which needs to be started separately), instead of... just connecting to the device(s) directly via USB/Serial? 

Obviously, this makes no sense when the Javascript (or Typescript) library is running in the context of the browser, but NodeJS is more than capable of using a serial connection (same as Python, Java, C++, etc. etc.) or even loading C++ modules if necessary. Any plans to make a proper ("native") NodeJS library?

**Comment by yoctopuce** [comment]
The Yoctopuce library is not based on serial connections. It uses vendor-specific HID packets to avoid the nightmare of serial ports getting mixed up. For this reason, we cannot use a standard node.js library to talk with them.
We could actually use our low-level shared library as we have done for other languages like Python, C# and Java, but so far we did not do it as it felt more natural that the library stays 100% in TypeScript, and to use a socket interface for low-level communication. But I am taking note of your request and this might come up in our list if other request it...

**Comment by anselanza** [comment]
> more natural that the library stays 100% in TypeScript

Perhaps, but having a requirement to run a separate process (VirtualHub) _and_ rely on a websocket connection behind the scenes seems worse, at least to me. (For now, in my own project, I find it more convenient to package the `YLightSensor` command-line binary, exec it from NodeJS and parse the output text, rather than deal with all of the above.)

Plenty of other NodeJS libraries include native/C/C++ libraries. (I can think of [MIDI](https://www.npmjs.com/package/midi) and [AbletonLink](https://www.npmjs.com/package/abletonlink-addon) libraries which I've used just recently, as examples). I accept that this certainly requires effort, but it's definitely a common practice for NodeJS libraries.

**Comment by yoctopuce** [comment]
Bundling C++ source code in the base library as done in these projects would add non-obvious prerequisites to install the library, so we would rather do that as an optional plug-in to avoid introducing a breaking change. But we will think about it.
